### ISSUE TITLE
W4. Annotate List<Device> getDevices in DeviceCategory.Java @XmlTransient

### ISSUE THREAD

**Issue by balazs-gabonyi** [codingmentor/eszkoznyilvantarto#59]
[SourceFile @Line 51](https://github.com/codingmentor/eszkoznyilvantarto/blob/feature/commonEntities/Common/src/main/java/entity/DeviceCategory.java)

**Comment by balazs-gabonyi** [comment]
Miki, ez azért kéne, mert a serializálásnál (végleten serializálási) gondot okozhat (szerintem).

**Comment by hegedus-peter** [comment]
Fixed in another refactor issue.
